version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_clothes_shop
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clothes_shop
      MYSQL_USER: clothes_shop
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
