services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: unless-stopped
    ports:
      - '${PORT:-4446}:4446'
    environment:
      - PORT=${PORT:-4446}
      - API_PREFIX=${API_PREFIX:-api}
      - API_DEFAULT_VERSION=${API_DEFAULT_VERSION:-1}

      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER_NAME=${DB_USER_NAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-DB_PASSWORD}
      - DB_NAME=${DB_NAME:-DB_NAME}

      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN:-15m}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN:-1d}
      - VERIFICATION_TOKEN_EXPIRES_IN=${VERIFICATION_TOKEN_EXPIRES_IN:-5m}

      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-REDIS_PASSWORD}

      - MINIO_HOST=${MINIO_HOST:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_ACCESSKEY=${MINIO_ACCESSKEY:-MINIO_ACCESSKEY}
      - MINIO_SECRETKEY=${MINIO_SECRETKEY:-MINIO_SECRETKEY}
      - BASE_IMAGE_URL=http://minio:${MINIO_PORT:-9000}/images/

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

      - KAFKA_BROKER=${KAFKA_BROKER:-kafka:29092}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
